### ISSUE TITLE
<Epic> Create a booking for a train ride.

### ISSUE THREAD

**Issue by MikeBot** [MikeBot/TGVTicketSales#10]
- [ ] Select planned train ride from search overview.
- [ ] Business class or Economic class. (seats are associated to one or another).
- [ ] Check if there are seats available.
- [ ] Every seat has a number.
- [ ] One ticket per seat.
- [ ] A name must be entered per seat.
- [ ] Customer must be logged-in to book.
- [ ] Bookings are added to a shopping cart.
- [ ] Maximum of tickets per booking.
