### ISSUE TITLE
<Epic> Make an order.

### ISSUE THREAD

**Issue by MikeBot** [MikeBot/TGVTicketSales#11]
Place an order for the tickets in the shoppingcart:

- [ ] Name
- [ ] payment methods
- [ ] Insurance
- [ ] Contact info
- [ ] Auto fill when information already in DB.
- [ ] Success page after successful order placement.
- [ ] Subtotal and total.
