### ISSUE TITLE
<Epic> Send confirmation mail after successful order placement.

### ISSUE THREAD

**Issue by MikeBot** [MikeBot/TGVTicketSales#14]
- [ ] Reseach law around order placement and confirmation mail.
- [ ] Reseach how to send mail after order placement. 
- [ ] Send confirmation mail.
