### ISSUE TITLE
<Epic> Introduction(home) page.

### ISSUE THREAD

**Issue by MikeBot** [MikeBot/TGVTicketSales#15]
- [ ] search functionality for rides.
- [ ] link to login / registration.
- [ ] short explanation of the site.
