### ISSUE TITLE
<Epic> Administration functions.

### ISSUE THREAD

**Issue by MikeBot** [MikeBot/TGVTicketSales#17]
- [ ] Change train schedule.
- [ ] Add other admins.
- [ ] Order Overview.
- [ ] Cancel orders/ticket.
