### ISSUE TITLE
<Task> Fill the project backlog with features and plan milestones

### ISSUE THREAD

**Issue by MikeBot** [MikeBot/TGVTicketSales#3]
- [x] Analyse the project description.
- [x] Fill the product backlog with features (epics, user stories,...) according to attached file.
- [x] Plan rough milestones (Milestones will be refined in sprint planning)

[ASPOpdrachtomschrijving_treinritten.pdf](https://github.com/MikeBot/TGVTicketSales/files/3388282/ASPOpdrachtomschrijving_treinritten.pdf)
