### ISSUE TITLE
<Epic> ShoppingCart.

### ISSUE THREAD

**Issue by MikeBot** [MikeBot/TGVTicketSales#5]
- [ ] Tickets are added to a shopping cart.
- [ ] A customer can get an overview of the shopping cart's content.
- [ ] From the shopping cart, the tickets can be booked.
