### ISSUE TITLE
<Epic> Overview orders for customer.

### ISSUE THREAD

**Issue by MikeBot** [MikeBot/TGVTicketSales#6]
- [ ] Historic overview of orders made by a customer.
- [ ] Has a status. (Completed, Sent, In processing, ...)
- [ ] Tickets booked related to order and its details.
