### ISSUE TITLE
<Epic> Overview of all train rides.

### ISSUE THREAD

**Issue by MikeBot** [MikeBot/TGVTicketSales#8]
- [ ] Overview of all train rides.
- [ ] Atleast one ride per day.
- [ ] Cities: Brussels, London, Paris, Amsterdam, Berlin, Rome and Moscow.
- [ ] Departures possible from all cities.
- [ ] Ride transfers in Brussels: 
        - All departures to and from London.
        - Paris - Amsterdam
        - Rome - Amsterdam
- [ ] Ride transfers in Berlin:
        - All departures to and from Moscow
