### ISSUE TITLE
<Epic> Search ride.

### ISSUE THREAD

**Issue by MikeBot** [MikeBot/TGVTicketSales#9]
- [ ] From - To station.
- [ ] Date and time (arrive/leave at).
- [ ] Overview matching criteria.
